default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sneakers_development

test:
  <<: *default
  database: sneakers_test

production:
  <<: *default
  database: sneakers_production
  username: mtovtin
  password: <%= ENV['SNEAKERS_DATABASE_PASSWORD'] %>